# Generated by Django 5.2.5 on 2025-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportPlus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('suggestion', 'Improvement Suggestion'), ('complaint', 'Complaint'), ('praise', 'Praise'), ('bug_report', 'Bug Report')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
    ]
