# Generated by Django 5.2.5 on 2025-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportPlus', '0002_contact_feedback_feedback_type_feedback_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('suggestion', 'Improvement Suggestion'), ('complaint', 'Complaint'), ('praise', 'Praise'), ('bug_report', 'Bug Report')], default='general', max_length=20),
            preserve_default=False,
        ),
    ]
