# Generated by Django 5.2.5 on 2025-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportPlus', '0003_delete_contact_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'General'), ('suggestion', 'Improvement Suggestion'), ('complaint', 'Complaint'), ('praise', 'Praise'), ('bug_report', 'Bug Report')], default='general', max_length=20),
        ),
    ]
