# Generated by Django 4.2.23 on 2025-08-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(default='hackathons_logos/default.jpg', upload_to='hackathons_logos/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_team_size', models.IntegerField()),
                ('min_team_size', models.IntegerField()),
                ('status', models.CharField(choices=[('OPENED', 'Opened'), ('CLOSED', 'Closed'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_track', to='dashboard.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_team', to='dashboard.hackathon')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_track', to='dashboard.hackathontrack')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submission', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('linedin', models.URLField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], default='personal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_payment', to='dashboard.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=100)),
                ('judge_email', models.EmailField(max_length=100)),
                ('judge_phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_judges', to='dashboard.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_judges_notes', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('TEAM', 'Team'), ('MEMBER', 'Member')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_request', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_request', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_stage', to='dashboard.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_requirement', to='dashboard.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_prize', to='dashboard.hackathon')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='dashboard.team')),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_stage', to='dashboard.hackathonstage'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_organization', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attend_status', models.CharField(choices=[('ATTEND', 'Attend'), ('ABSENT', 'Absent')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_attend', to='dashboard.team')),
            ],
        ),
    ]
