# Generated by Django 4.2.23 on 2025-08-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_hackathon_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linedin',
            new_name='linkedin',
        ),
    ]
