# Generated by Django 4.2.23 on 2025-08-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='hackathon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_payment', to='dashboard.hackathon'),
        ),
    ]
