# Generated by Django 4.2.23 on 2025-08-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_payment_hackathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_track', to='dashboard.hackathontrack'),
        ),
    ]
