# Generated by Django 4.2.23 on 2025-08-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_linedin_profile_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgenote',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='judgenote',
            name='judge_email',
        ),
        migrations.RemoveField(
            model_name='judgenote',
            name='judge_name',
        ),
        migrations.RemoveField(
            model_name='judgenote',
            name='judge_phone',
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=100)),
                ('judge_email', models.EmailField(max_length=100)),
                ('judge_phone', models.CharField(max_length=100)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_judges', to='dashboard.hackathon')),
            ],
        ),
        migrations.AddField(
            model_name='judgenote',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_judges_notes', to='dashboard.judge'),
            preserve_default=False,
        ),
    ]
