# Generated by Django 4.2.23 on 2025-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_judgenote_hackathon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(default='hackathons_logos/default.svg', upload_to='hackathons_logos/'),
        ),
    ]
