# Generated by Django 4.2.23 on 2025-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_profile_created_at_profile_behance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITING', 'Waiting')], default='WAITING', max_length=100),
            preserve_default=False,
        ),
    ]
