# Generated by Django 4.2.23 on 2025-08-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_team_track', to='dashboard.hackathontrack'),
        ),
    ]
