# Generated by Django 4.2.23 on 2025-08-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_team_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgenote',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges_notes', to='dashboard.judge'),
        ),
        migrations.AlterField(
            model_name='judgenote',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notes', to='dashboard.team'),
        ),
    ]
