# Generated by Django 4.2.23 on 2025-09-01 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_alter_judgenote_judge_alter_judgenote_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITING', 'Waiting')], default='WAITING', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('member', 'team')},
        ),
    ]
