# Generated by Django 4.2.23 on 2025-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_team_status_alter_teammember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubmission',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamsubmission',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
